[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "busywork"
description = "A package for managing dependency groups."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "GPL-v2" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = ["pip", "toml", "dahlia"]
version = "0.1.0"

[tool.setuptools]
packages = ["busywork"]

[tool.busywork.groups.dev]
requires = ["nox"]
requires-groups = ["linting", "typing"]

[tool.busywork.groups.linting]
requires = ["black", "isort"]

[tool.busywork.groups.typing]
requires = ["mypy", "types-toml"]

[project.scripts]
busywork = "busywork.__main__:main"
